-- Enable Row Level Security (RLS) is recommended for all tables
-- Create tables in public schema

-- 1. Profiles (extends auth.users)
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamptz default now(),
  primary key (id)
);

alter table public.profiles enable row level security;

create policy "Users can view their own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. Exercises
create table public.exercises (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  muscle text,
  created_at timestamptz default now()
);

alter table public.exercises enable row level security;

create policy "Users can view their own exercises" on public.exercises
  for select using (auth.uid() = user_id);

create policy "Users can insert their own exercises" on public.exercises
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own exercises" on public.exercises
  for update using (auth.uid() = user_id);

create policy "Users can delete their own exercises" on public.exercises
  for delete using (auth.uid() = user_id);


-- 3. Sessions (Workouts)
create table public.sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date timestamptz default now(),
  score numeric,
  volume numeric,
  avg_rpe numeric,
  created_at timestamptz default now()
);

alter table public.sessions enable row level security;

create policy "Users can all CRUD their own sessions" on public.sessions
  for all using (auth.uid() = user_id);


-- 4. Workout Entries (Exercises within a session)
create table public.workout_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  session_id bigint references public.sessions on delete cascade,
  exercise_id bigint references public.exercises on delete cascade,
  sets jsonb, -- Storing sets as JSONB array [{reps: 10, weight: 100, rpe: 8}, ...]
  date timestamptz default now()
);

alter table public.workout_entries enable row level security;

create policy "Users can all CRUD their own entries" on public.workout_entries
  for all using (auth.uid() = user_id);
